### ISSUE TITLE
Name is offensive

### ISSUE THREAD

**Issue by kulinacs** [Mustard1/SQLsUCK#1]
The name of this project is offensive. Please consider some less alternatives, like:

* SQLcouldusesomeimprovement
* SQLhaslotsofpotential
* SQLhasroomtogrow
* SQListryingitsbest

**Comment by MustardJuan** [comment]
Thank you for the feedback as we are always looking for ways to improve our products, we value user feedback. The name has been changed to be more inclusive to the development landscape. Thank you and we look forward to hearing more from you in the future.
